import type { AdPackage, MarketplaceProperty } from './types'

export const marketplaceSampleProperties: MarketplaceProperty[] = [
  {
    id: 'sample-1',
    title: 'شقة فندقية كاملة التشطيب في التجمع الخامس',
    description: 'وحدة جاهزة للسكن داخل كمبوند مخدوم بالقرب من محور محمد نجيب.',
    price: 3850000,
    currency: 'EGP',
    listingKind: 'resale',
    propertyType: 'شقة',
    city: 'القاهرة الجديدة',
    district: 'التجمع الخامس',
    location: 'التجمع الخامس، القاهرة الجديدة',
    areaSqm: 156,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80',
    featured: true,
    urgent: false,
    status: 'approved',
    viewsCount: 1280,
    seller: {
      name: 'EHAB & ESLAM TEAM',
      type: 'broker',
      rating: 4.9,
      verified: true,
    },
    createdAt: '2026-04-14',
  },
  {
    id: 'sample-2',
    title: 'فيلا مستقلة بحديقة خاصة في الشروق',
    description: 'مساحات عائلية واسعة وتشطيب راق داخل منطقة هادئة قريبة من الخدمات.',
    price: 9800000,
    currency: 'EGP',
    listingKind: 'resale',
    propertyType: 'فيلا',
    city: 'الشروق',
    district: 'الحي الثامن',
    location: 'مدينة الشروق، القاهرة',
    areaSqm: 420,
    bedrooms: 5,
    bathrooms: 4,
    imageUrl: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80',
    featured: false,
    urgent: true,
    status: 'approved',
    viewsCount: 734,
    seller: {
      name: 'مالك موثق',
      type: 'individual',
      rating: 4.7,
      verified: true,
    },
    createdAt: '2026-04-13',
  },
  {
    id: 'sample-3',
    title: 'تاون هاوس استلام قريب في الشيخ زايد',
    description: 'طرح أول من المطور بخطة سداد مرنة ومقدم مناسب للاستثمار.',
    price: 7200000,
    currency: 'EGP',
    listingKind: 'primary',
    propertyType: 'تاون هاوس',
    city: 'الشيخ زايد',
    district: 'زايد الجديدة',
    location: 'زايد الجديدة، الجيزة',
    areaSqm: 235,
    bedrooms: 4,
    bathrooms: 3,
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80',
    featured: true,
    urgent: false,
    status: 'approved',
    viewsCount: 2190,
    seller: {
      name: 'Developer Partner',
      type: 'developer',
      rating: 4.8,
      verified: true,
    },
    createdAt: '2026-04-12',
  },
]

export const marketplacePackages: AdPackage[] = [
  { id: 'individual-1', name: 'إعلان فردي', audience: 'individual', price: 150, adsIncluded: 1, featuredAds: 0, verifiedBadge: false },
  { id: 'individual-4', name: 'باقة 4 إعلانات', audience: 'individual', price: 500, adsIncluded: 4, featuredAds: 0, verifiedBadge: false },
  { id: 'individual-12', name: 'باقة 12 إعلان', audience: 'individual', price: 1000, adsIncluded: 12, featuredAds: 0, verifiedBadge: false },
  { id: 'company-15', name: 'باقة شركات', audience: 'company', price: 3000, adsIncluded: 15, featuredAds: 3, verifiedBadge: false },
  { id: 'company-60', name: 'باقة شركات موثقة', audience: 'company', price: 10000, adsIncluded: 60, featuredAds: 6, verifiedBadge: true },
]
